import { describe, expect, it } from 'vitest'
import '../content/verbs'
import { conjugate, type TenseId } from './conjugate'

const f = (inf: string, t: TenseId) => conjugate(inf).forms[t].join(', ')

describe('regular verbs', () => {
  it('present', () => {
    expect(f('hablar', 'pres')).toBe('hablo, hablas, habla, hablamos, habláis, hablan')
    expect(f('comer', 'pres')).toBe('como, comes, come, comemos, coméis, comen')
    expect(f('vivir', 'pres')).toBe('vivo, vives, vive, vivimos, vivís, viven')
  })
  it('past tenses', () => {
    expect(f('comer', 'pret')).toBe('comí, comiste, comió, comimos, comisteis, comieron')
    expect(f('hablar', 'pret')).toBe('hablé, hablaste, habló, hablamos, hablasteis, hablaron')
    expect(f('vivir', 'impf')).toBe('vivía, vivías, vivía, vivíamos, vivíais, vivían')
    expect(f('hablar', 'impf')).toBe('hablaba, hablabas, hablaba, hablábamos, hablabais, hablaban')
  })
  it('future, conditional, subjunctive', () => {
    expect(f('hablar', 'fut')).toBe('hablaré, hablarás, hablará, hablaremos, hablaréis, hablarán')
    expect(f('comer', 'cond')).toBe('comería, comerías, comería, comeríamos, comeríais, comerían')
    expect(f('hablar', 'subj')).toBe('hable, hables, hable, hablemos, habléis, hablen')
    expect(f('vivir', 'subj')).toBe('viva, vivas, viva, vivamos, viváis, vivan')
    expect(f('hablar', 'impsubj')).toBe('hablara, hablaras, hablara, habláramos, hablarais, hablaran')
  })
  it('compound tenses', () => {
    expect(conjugate('hablar').forms.perf[0]).toBe('he hablado')
    expect(conjugate('comer').forms.plus[3]).toBe('habíamos comido')
    expect(conjugate('vivir').forms.futp[5]).toBe('habrán vivido')
    expect(conjugate('hacer').forms.subjp[0]).toBe('haya hecho')
  })
  it('imperative', () => {
    expect(f('hablar', 'imp')).toBe(', habla, hable, hablemos, hablad, hablen')
    expect(f('comer', 'impneg')).toBe(', no comas, no coma, no comamos, no comáis, no coman')
  })
})

describe('irregular verbs', () => {
  it('ser / estar / ir / haber', () => {
    expect(f('ser', 'pres')).toBe('soy, eres, es, somos, sois, son')
    expect(f('ser', 'impsubj')).toBe('fuera, fueras, fuera, fuéramos, fuerais, fueran')
    expect(f('estar', 'pret')).toBe('estuve, estuviste, estuvo, estuvimos, estuvisteis, estuvieron')
    expect(f('estar', 'subj')).toBe('esté, estés, esté, estemos, estéis, estén')
    expect(f('ir', 'imp')).toBe(', ve, vaya, vamos, id, vayan')
    expect(f('ir', 'impf')).toBe('iba, ibas, iba, íbamos, ibais, iban')
    expect(conjugate('ir').ger).toBe('yendo')
    expect(f('haber', 'pres')).toBe('he, has, ha, hemos, habéis, han')
    expect(conjugate('ser').forms.imp[1]).toBe('sé')
    expect(conjugate('estar').forms.imp[1]).toBe('está')
  })
  it('tener / venir / poner / salir / hacer / decir', () => {
    expect(f('tener', 'pres')).toBe('tengo, tienes, tiene, tenemos, tenéis, tienen')
    expect(f('tener', 'pret')).toBe('tuve, tuviste, tuvo, tuvimos, tuvisteis, tuvieron')
    expect(conjugate('tener').forms.fut[0]).toBe('tendré')
    expect(conjugate('tener').forms.subj[0]).toBe('tenga')
    expect(conjugate('tener').forms.imp[1]).toBe('ten')
    expect(conjugate('venir').forms.pret.join(', ')).toBe('vine, viniste, vino, vinimos, vinisteis, vinieron')
    expect(conjugate('venir').ger).toBe('viniendo')
    expect(conjugate('poner').part).toBe('puesto')
    expect(conjugate('poner').forms.pret[0]).toBe('puse')
    expect(conjugate('salir').forms.pres[0]).toBe('salgo')
    expect(conjugate('salir').forms.fut[0]).toBe('saldré')
    expect(f('hacer', 'pret')).toBe('hice, hiciste, hizo, hicimos, hicisteis, hicieron')
    expect(conjugate('hacer').part).toBe('hecho')
    expect(conjugate('hacer').forms.imp[1]).toBe('haz')
    expect(conjugate('hacer').forms.fut[0]).toBe('haré')
    expect(f('decir', 'pret')).toBe('dije, dijiste, dijo, dijimos, dijisteis, dijeron')
    expect(conjugate('decir').ger).toBe('diciendo')
    expect(conjugate('decir').forms.fut[0]).toBe('diré')
    expect(conjugate('decir').forms.impsubj[3]).toBe('dijéramos')
  })
  it('poder / querer / saber / dar / ver / traer / caer / oír', () => {
    expect(f('poder', 'pres')).toBe('puedo, puedes, puede, podemos, podéis, pueden')
    expect(conjugate('poder').ger).toBe('pudiendo')
    expect(conjugate('querer').forms.pret[0]).toBe('quise')
    expect(conjugate('querer').forms.fut[0]).toBe('querré')
    expect(conjugate('saber').forms.pres[0]).toBe('sé')
    expect(conjugate('saber').forms.subj[0]).toBe('sepa')
    expect(conjugate('saber').forms.pret[2]).toBe('supo')
    expect(f('dar', 'pret')).toBe('di, diste, dio, dimos, disteis, dieron')
    expect(conjugate('dar').forms.subj[0]).toBe('dé')
    expect(f('ver', 'pret')).toBe('vi, viste, vio, vimos, visteis, vieron')
    expect(conjugate('ver').part).toBe('visto')
    expect(f('traer', 'pret')).toBe('traje, trajiste, trajo, trajimos, trajisteis, trajeron')
    expect(conjugate('traer').ger).toBe('trayendo')
    expect(conjugate('caer').forms.pres[0]).toBe('caigo')
    expect(f('caer', 'pret')).toBe('caí, caíste, cayó, caímos, caísteis, cayeron')
    expect(f('oír', 'pres')).toBe('oigo, oyes, oye, oímos, oís, oyen')
    expect(conjugate('oír').forms.fut[0]).toBe('oiré')
    expect(conjugate('oír').forms.imp[4]).toBe('oíd')
  })
})

describe('stem-changing & spelling-change verbs', () => {
  it('-ir stem changers', () => {
    expect(f('pedir', 'pres')).toBe('pido, pides, pide, pedimos, pedís, piden')
    expect(f('pedir', 'pret')).toBe('pedí, pediste, pidió, pedimos, pedisteis, pidieron')
    expect(f('pedir', 'subj')).toBe('pida, pidas, pida, pidamos, pidáis, pidan')
    expect(conjugate('pedir').ger).toBe('pidiendo')
    expect(f('dormir', 'pret')).toBe('dormí, dormiste, durmió, dormimos, dormisteis, durmieron')
    expect(conjugate('dormir').forms.subj[3]).toBe('durmamos')
    expect(conjugate('dormir').ger).toBe('durmiendo')
    expect(conjugate('sentir').forms.pret[2]).toBe('sintió')
    expect(conjugate('sentir').forms.subj.join(', ')).toBe('sienta, sientas, sienta, sintamos, sintáis, sientan')
    expect(conjugate('preferir').forms.pres[0]).toBe('prefiero')
    expect(conjugate('morir').part).toBe('muerto')
    expect(conjugate('morir').forms.pret[2]).toBe('murió')
  })
  it('-ar / -er stem changers', () => {
    expect(f('jugar', 'pres')).toBe('juego, juegas, juega, jugamos, jugáis, juegan')
    expect(conjugate('jugar').forms.pret[0]).toBe('jugué')
    expect(conjugate('jugar').forms.subj.join(', ')).toBe('juegue, juegues, juegue, juguemos, juguéis, jueguen')
    expect(conjugate('empezar').forms.pres[0]).toBe('empiezo')
    expect(conjugate('empezar').forms.pret[0]).toBe('empecé')
    expect(conjugate('empezar').forms.subj[3]).toBe('empecemos')
    expect(conjugate('volver').part).toBe('vuelto')
    expect(conjugate('volver').forms.pres[0]).toBe('vuelvo')
    expect(conjugate('almorzar').forms.pres[0]).toBe('almuerzo')
    expect(conjugate('almorzar').forms.pret[0]).toBe('almorcé')
  })
  it('spelling changes', () => {
    expect(conjugate('buscar').forms.pret[0]).toBe('busqué')
    expect(conjugate('buscar').forms.subj[0]).toBe('busque')
    expect(conjugate('llegar').forms.pret[0]).toBe('llegué')
    expect(conjugate('conocer').forms.pres[0]).toBe('conozco')
    expect(conjugate('conocer').forms.subj[0]).toBe('conozca')
    expect(conjugate('conducir').forms.pres[0]).toBe('conduzco')
    expect(f('conducir', 'pret')).toBe('conduje, condujiste, condujo, condujimos, condujisteis, condujeron')
    expect(conjugate('seguir').forms.pres.slice(0, 2).join(', ')).toBe('sigo, sigues')
    expect(conjugate('seguir').forms.pret[2]).toBe('siguió')
    expect(conjugate('elegir').forms.pres[0]).toBe('elijo')
    expect(conjugate('coger').forms.pres[0]).toBe('cojo')
    expect(conjugate('convencer').forms.pres[0]).toBe('convenzo')
  })
  it('-uir and vowel stems', () => {
    expect(f('construir', 'pres')).toBe('construyo, construyes, construye, construimos, construís, construyen')
    expect(f('construir', 'pret')).toBe('construí, construiste, construyó, construimos, construisteis, construyeron')
    expect(conjugate('construir').ger).toBe('construyendo')
    expect(conjugate('construir').part).toBe('construido')
    expect(f('leer', 'pret')).toBe('leí, leíste, leyó, leímos, leísteis, leyeron')
    expect(conjugate('leer').part).toBe('leído')
    expect(conjugate('leer').ger).toBe('leyendo')
  })
  it('accent verbs', () => {
    expect(f('enviar', 'pres')).toBe('envío, envías, envía, enviamos, enviáis, envían')
    expect(conjugate('enviar').forms.imp[1]).toBe('envía')
    expect(conjugate('continuar').forms.pres[0]).toBe('continúo')
    expect(conjugate('reunirse').forms.pres[0]).toBe('me reúno')
  })
})

describe('compounds & reflexives', () => {
  it('prefixed verbs', () => {
    expect(conjugate('mantener').forms.pres.slice(0, 2).join(', ')).toBe('mantengo, mantienes')
    expect(conjugate('mantener').forms.imp[1]).toBe('mantén')
    expect(conjugate('mantener').forms.fut[0]).toBe('mantendré')
    expect(conjugate('devolver').part).toBe('devuelto')
    expect(conjugate('componer').forms.imp[1]).toBe('compón')
    expect(conjugate('componer').part).toBe('compuesto')
    expect(f('prever', 'pres')).toBe('preveo, prevés, prevé, prevemos, prevéis, prevén')
    expect(conjugate('prever').forms.pret[2]).toBe('previó')
    expect(conjugate('sonreír').forms.pres[0]).toBe('sonrío')
    expect(conjugate('sonreír').forms.pret[2]).toBe('sonrió')
    expect(conjugate('descubrir').part).toBe('descubierto')
    expect(conjugate('deshacer').forms.pres[0]).toBe('deshago')
  })
  it('reflexive verbs', () => {
    expect(conjugate('levantarse').forms.pres[0]).toBe('me levanto')
    expect(conjugate('levantarse').forms.perf[2]).toBe('se ha levantado')
    expect(f('levantarse', 'imp')).toBe(', levántate, levántese, levantémonos, levantaos, levántense')
    expect(conjugate('levantarse').forms.impneg[1]).toBe('no te levantes')
    expect(conjugate('levantarse').ger).toBe('levantándose')
    expect(conjugate('vestirse').forms.imp[1]).toBe('vístete')
    expect(conjugate('vestirse').forms.imp[4]).toBe('vestíos')
    expect(f('irse', 'imp')).toBe(', vete, váyase, vámonos, idos, váyanse')
    expect(conjugate('sentarse').forms.imp[1]).toBe('siéntate')
    expect(conjugate('ponerse').forms.imp[1]).toBe('ponte')
    expect(conjugate('ponerse').forms.imp[2]).toBe('póngase')
    expect(conjugate('dormirse').forms.imp[1]).toBe('duérmete')
    expect(conjugate('reírse').forms.imp[1]).toBe('ríete')
    expect(conjugate('caerse').forms.imp[1]).toBe('cáete')
    expect(conjugate('acostarse').forms.pres[0]).toBe('me acuesto')
    expect(conjugate('divertirse').forms.pret[2]).toBe('se divirtió')
  })
})
