/* High-frequency function words, so tapping almost any word in a text gives a translation. */
export const CORE = `
el = the (masc.)
la = the (fem.); her, it (object)
los = the (masc. pl.); them (object)
las = the (fem. pl.); them (fem., object)
lo = it, him (object); the … thing
un = a, an (masc.)
una = a, an (fem.)
unos = some (masc.)
unas = some (fem.)
de = of, from
del = of the (de + el)
a = to, at
al = to the (a + el)
en = in, on, at
con = with
sin = without
por = for, by, through, because of
para = for, in order to
y = and
e = and (before i- / hi-)
o = or
u = or (before o- / ho-)
pero = but
sino = but rather
que = that, which, who; than
qué = what, which; how (¡qué…!)
quién = who
quiénes = who (plural)
cómo = how
cuándo = when
dónde = where
adónde = where to
cuánto = how much
cuánta = how much
cuántos = how many
cuántas = how many
cuál = which (one)
cuáles = which (ones)
porque = because
si = if, whether
sí = yes
no = no, not
ni = nor, not even
también = also, too
tampoco = neither, not either
muy = very
mucho = a lot, much
mucha = a lot of, much
muchos = many
muchas = many
poco = little, not much
poca = little
pocos = few
pocas = few
más = more
menos = less, fewer; minus
ya = already; now
todavía = still, yet
aún = still, yet
siempre = always
nunca = never
jamás = never (ever)
hoy = today
ayer = yesterday
mañana = tomorrow; morning
ahora = now
luego = later, then
después = after, afterwards
antes = before
entonces = then, so
aquí = here
allí = there
ahí = there (near you)
este = this (masc.)
esta = this (fem.)
estos = these (masc.)
estas = these (fem.)
esto = this (thing)
ese = that (masc.)
esa = that (fem.)
esos = those (masc.)
esas = those (fem.)
eso = that (thing)
aquel = that (over there)
aquella = that (over there, fem.)
mi = my
mis = my (plural)
tu = your
tus = your (plural)
su = his, her, its, their, your (formal)
sus = his, her, their, your (plural things)
nuestro = our
nuestra = our
vuestro = your (you all)
vuestra = your (you all)
me = me, to me, myself
te = you, to you, yourself
se = himself, herself, themselves; (impersonal) one
nos = us, to us, ourselves
os = you all, to you all
le = to him, to her, to you (formal)
les = to them, to you all
mí = me (after a preposition)
ti = you (after a preposition)
conmigo = with me
contigo = with you
todo = all, everything
toda = all, the whole
todos = all, everyone
todas = all
otro = other, another
otra = other, another
otros = others
otras = others
algo = something
nada = nothing
alguien = someone
nadie = nobody
algún = some, any
alguno = some, any (one)
alguna = some, any
ningún = no, not any
ninguno = none, no one
ninguna = none, no
cada = each, every
bien = well, fine
mal = badly, bad
así = like this, so
hay = there is, there are
sobre = on, about
entre = between, among
hasta = until, up to; even
desde = from, since
hacia = towards
contra = against
según = according to
durante = during
mientras = while
cuando = when
donde = where
como = like, as; since
aunque = although, even if
tan = so, as
tanto = so much, as much
bastante = quite, enough
demasiado = too, too much
casi = almost
solo = only; alone
señor = sir, Mr, gentleman
señora = madam, Mrs, lady
don = title of respect (Mr)
doña = title of respect (Mrs)
vale = OK, fine (Spain)
bueno = well…; good
pues = well…, then
vamos = let's go; come on
venga = come on! (Spain)
oye = hey, listen
mira = look
claro = of course, clear
`
